// ============================================================
// Azure Communication Services + Email Service
// Project: IPELRA Conference Passport
// Used for: magic link delivery + completion congratulations emails
// ============================================================

@description('Resource tags')
param tags object

// ── Email Service ─────────────────────────────────────────────
// Must be created before the Communication Service so we can
// link the managed domain.
resource emailService 'Microsoft.Communication/emailServices@2023-03-31' = {
  name: 'email-ipelra-passport'
  // ACS Email resources must be in 'global' location
  location: 'global'
  tags: tags
  properties: {
    dataLocation: 'United States'
  }
}

// ── Azure Managed Email Domain ────────────────────────────────
// Provisions a free Azure-managed sender domain (*.azurecomm.net).
// Sender address will be: DoNotReply@<auto-generated>.azurecomm.net
//
// NOTE: For improved deliverability and branded sender address,
// configure a custom domain with SPF/DKIM records post-deploy.
// See README > Post-Deploy Steps for instructions.
resource managedDomain 'Microsoft.Communication/emailServices/domains@2023-03-31' = {
  parent: emailService
  name: 'AzureManagedDomain'
  location: 'global'
  properties: {
    domainManagement: 'AzureManaged'
    userEngagementTracking: 'Disabled'
  }
}

// ── Communication Service ─────────────────────────────────────
// The main ACS resource. Linked to the email domain above.
// Created after domain to satisfy the linkedDomains reference.
resource communicationService 'Microsoft.Communication/communicationServices@2023-03-31' = {
  name: 'acs-ipelra-passport'
  location: 'global'
  tags: tags
  properties: {
    dataLocation: 'United States'
    linkedDomains: [
      managedDomain.id
    ]
  }
}

// ── Outputs ──────────────────────────────────────────────────
output acsConnectionString string = communicationService.listKeys().primaryConnectionString
// The Azure-managed sender domain (e.g. abc123.azurecomm.net)
// Sender address will be DoNotReply@<senderDomain>
output senderDomain string = managedDomain.properties.mailFromSenderDomain
output communicationServiceName string = communicationService.name
